scheduler:
  resources:
   limits:
    memory: 512Mi
   requests:
    cpu: 100m
    memory: 512Mi
webserver:
  resources:
   limits:
    memory: 2Gi
   requests:
    cpu: 100m
    memory: 2Gi
worker:
  resources:
   limits:
    memory: 512Mi
   requests:
    cpu: 100m
    memory: 512Mi
redis:
  resources:
   limits:
    memory: 128Mi
   requests:
    cpu: 100m
    memory: 128Mi
  password: admin
postgresql:
  resources:
   limits:
    memory: 128Mi
   requests:
    cpu: 100m
    memory: 128Mi
triggerer:
  enabled: false

statsd:
  resources:
   limits:
    memory: 128Mi
   requests:
    cpu: 100m
    memory: 128Mi

executor: "CeleryKubernetesExecutor"
dags:
  gitSync:
    enabled: true
    repo: https://github.com/bench87/example-dags.git
    branch: main
    subPath: dags
